---
# tasks file for xi_aide
- name: install aide
  yum:
    name: aide
    state: latest

- name: Customze aide.conf for Nagios XI
  blockinfile:
    dest: /etc/aide.conf
    backup: yes
    marker: "#-- {mark} ANSIBLE MANAGED BLOCK -->"
    insertafter: "These are too volatile"
    content: |
     # Conclusion Xforce: additional settings for Nagios
     !/usr/local/ncpa/var
     !/usr/local/nagios/etc
     !/usr/local/databases
     !/usr/local/nagios/var
     !/usr/local/nagios/share/perfdata
     !/usr/local/mrtg
     !/usr/local/nagiosxi/var
     !/usr/local/nagiosxi/scripts
     !/usr/local/nagiosxi/nom
     !/var/log/httpd
     !/var/log/audit
     !/var/log/rhsm

- name: Customze aide.conf default output
  lineinfile:
    dest: /etc/aide.conf
    backup: yes
    regexp: 'database_out=file:@@{DBDIR}/aide.db.new.gz'
    line: 'database_out=file:@@{DBDIR}/aide.db.gz'
    backrefs: yes

- name: Schedule aide init check
  shell: 'nohup aide --init &'
  args: 
    chdir: /tmp
   
