---
# Playbook that configures Nagios clients (either update or new install) with Nagios Cross Platform Agent (NCPA)
# 
# gather_facts: false
- hosts: nagios-clients-linux
  become: true
  roles:
    - nagiosrepo
    - ncpa_rhel

- hosts: nagios-clients-windows
  become: false
  roles:
    - ncpa_win

#  tasks:
#    - include: ./tasks/main.yml
