---
# tasks file for xi_server_fullinstall

- name: Get software
  get_url:
    dest: "{{ tmpdir }}/xi-latest.tar.gz"
    url: https://assets.nagios.com/downloads/nagiosxi/xi-latest.tar.gz
    force: no # if file exists don't download and go ahead. Normally you would need to get rid of old tarballs.

- name: Unzip XI tarball
  unarchive:
    src: "{{ tmpdir }}/xi-latest.tar.gz"
    dest: /tmp
    remote_src: True

- name: Run fullinstall script
  command: ./fullinstall -n
  args:
    chdir: "{{ tmpdir }}/nagiosxi"
  register: fullinstall_out

- name: Display results from fullinstall script
  debug:
    var: fullinstall_out
    verbosity: 1

- name: Jinja2 template for nagiosadmin setup
  template:
    src: xi_setup_nagiosadmin.bash.j2
    dest: /usr/local/bin/xi_setup_nagiosadmin.bash
    owner: root
    group: nagios
    mode: '0700'
 
# this step automates what install.php normally does by presenting a PHP form. Thanks Matthew Capra!
- name: Run nagiosadmin setup 
  command: /usr/local/bin/xi_setup_nagiosadmin.bash
  register: setupnagiosadmin_out
  args:
    creates: "{{ output_file }}"
