---
- name: check for old ncpa installation
  command: "rpm -q ncpa-1.8*"
  register: ncpa_old_version_exists
  changed_when: "ncpa_old_version_exists.rc == 0"

- name: remove old ncpa first
  yum
    name: ncpa
    state: absent
  when: "ncpa_old_version_exists.rc == 0"

- name: install ncpa client latest
  yum:
    name: ncpa
    state: latest
    enablerepo: nagios-base
  notify:
  - restart ncpa

- name:  ncpa listener service should be enabled
  service:
    name: ncpa_listener
    state: started
    enabled: true

- name: open firewall for ncpa
  firewalld:
    port: "{{ ncpa_port }}/tcp"
    state: enabled
    permanent: true
    immediate: true

# de lineinfile module vervangt helaas CRLF door CRLF,LF
#- name:  change token (community string)
#  lineinfile:
#    dest: /usr/local/ncpa/etc/ncpa.cfg
#    regexp: "^community_string ="
#    line: "community_string = MY7tdi#7"

- name:  change token (community string)
  replace:
    dest: /usr/local/ncpa/etc/ncpa.cfg
    backup: true
    regexp: '^community_string =.*$'
    replace: 'community_string = {{ ncpa_token }}'
  notify:
  - restart ncpa


- name: copy plugin hostname_selinux.sh
  copy:
    src: 'hostname_selinux.sh'
    dest: '/usr/local/ncpa/plugins/hostname_selinux.sh'
    owner: root
    mode: '750'

- name: copy plugin service_active.sh
  copy:
    src: 'service_active.sh'
    dest: '/usr/local/ncpa/plugins/service_active.sh'
    owner: root
    mode: '750'
