---
- name: Install repo file and package
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - http://repo.nagios.com/nagios/7/nagios-repo-7-2.el7.noarch.rpm
    - yum-utils
    - psmisc

#A command like this is not idempotent, so we have to use the yum_repository module
#- name: disable one specific repo
# command: yum-config-manager --disable nagiosxi-deps
  
- name: delete one specific repo from repo-file
  yum_repository: 
    name: nagiosxi-deps
    file: nagios-7
    state: absent
  

#- name: Repo for Nagios
#  copy:
#    src: 'nagios-7.repo'
#    dest: '/etc/yum.repos.d/'
#    owner: root
#    mode: '644'


  
