---
- name: Install repo file and package
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - http://repo.nagios.com/nagios/{{ ansible_distribution_major_version }}/nagios-repo-{{ ansible_distribution_major_version }}-4.el{{ ansible_distribution_major_version }}.noarch.rpm
    - yum-utils
    - psmisc

# Goal: Disable nagiosxi-deps repo from repo-file
# Possible command: yum-config-manager --disable nagiosxi-deps
# Note: A command like this is not idempotent, so we have to use the yum_repository module
  
- name: Disable nagiosxi-deps repo from repo-file
  yum_repository: 
    name: nagiosxi-deps
    file: nagios-{{ ansible_distribution_major_version }}
    state: absent
  when: not inventory_hostname == 'monitor'
  
