---
# This role depends on tasks from nagiosrepo role
#
- name: check for old ncpa installation
  command: "rpm -q ncpa-1.8*"
  register: ncpa_old_version_exists
  changed_when: "ncpa_old_version_exists.rc == 0"
  ignore_errors: true

- name:  old ncpa services should be stopped
  service:
    name: "{{ item }}"
    state: stopped
    enabled: false
  with_items:
    - ncpa_passive
    - ncpa_listener
  when: "ncpa_old_version_exists.changed"

- name: kill old processes because of ncpa 1.8 bug
  command: "killall -v {{ item }}"
  with_items:
    - ncpa_posix_passive
    - ncpa_posix_listener
  when: "ncpa_old_version_exists.changed"
  ignore_errors: true

- name: remove old ncpa 
  yum:
    name: ncpa
    state: absent
  when: "ncpa_old_version_exists.changed"


- name: install ncpa client latest
  yum:
    name: ncpa
    state: latest
    enablerepo: nagios-base
  notify:
  - restart ncpa

- name:  ncpa services should be enabled
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
    - ncpa_passive
    - ncpa_listener

- name: open firewall for ncpa
  firewalld:
    port: "{{ ncpa_port }}/tcp"
    state: enabled
    permanent: true
    immediate: true

# de lineinfile module vervangt helaas CRLF door CRLF,LF
#- name:  change token (community string)
#  lineinfile:
#    dest: /usr/local/ncpa/etc/ncpa.cfg
#    regexp: "^community_string ="
#    line: "community_string = MY7tdi#7"

- name:  change token (community string)
  replace:
    dest: /usr/local/ncpa/etc/ncpa.cfg
    backup: true
    regexp: '^community_string =.*$'
    replace: 'community_string = {{ ncpa_token | default("demo-token") }}'
  notify:
  - restart ncpa


- name: copy several ncpa plugins
  copy:
    src: "{{ item }}"
    dest: "/usr/local/ncpa/plugins/{{ item }}"
    owner: nagios
    mode: '750'
  with_items:
    - hostname_selinux.sh
    - service_active.sh
 
- name: Create import dir
  file:
    path: "/usr/local/nagios/etc/import/"
    state: directory
    owner: nagios
    mode: 0755
  delegate_to: 192.168.122.5

- name: template for nagios client hosts
  template:
    src: ../templates/host-linuxtemplate.cfg
    dest: "/usr/local/nagios/etc/import/host{{ inventory_hostname }}.cfg"
    owner: nagios
    group: nagios
    mode: '0755'
  delegate_to: 192.168.122.5

- name: template for nagios client services
  template:
    src: ../templates/svc-linuxtemplate.cfg
    dest: "/usr/local/nagios/etc/import/{{ inventory_hostname }}.cfg"
    owner: nagios
    group: nagios
    mode: '0755'
  delegate_to: 192.168.122.5
